=== zrnkemiki/XML_VS/xscience/data/user.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="User" type="TUser"> </xs:element>
    <xs:complexType name="TUser">
        <xs:sequence>
            <xs:element default="PUBLIC_USER" name="role">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="AUTHOR"/>
                        <xs:enumeration value="REVIEWER"/>
                        <xs:enumeration value="EDITOR"/>
                        <xs:enumeration value="PUBLIC_USER"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="email">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:pattern value="[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="password">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:minLength value="6"/>
                        <xs:maxLength value="40"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="first_name">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:minLength value="2"/>
                        <xs:maxLength value="30"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element minOccurs="0" name="middle-name">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:minLength value="1"/>
                        <xs:maxLength value="30"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="last-name">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:minLength value="2"/>
                        <xs:maxLength value="40"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element minOccurs="0" name="publications">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element maxOccurs="unbounded" minOccurs="0" name="publicationID"
                            type="xs:ID"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element minOccurs="0" name="publications_for_review">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element maxOccurs="unbounded" minOccurs="0" name="for_reviewID"
                            type="xs:ID"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== zrnkemiki/XML_VS/xscience/src/main/resources/data/valid-xml/user-author-gmail.com.xml
<?xml version="1.0" encoding="UTF-8"?>
<User xmlns="https://www.xscience.com/data/user.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://www.xscience.com/data/user.xsd user.xsd ">
  <role>ROLE_AUTHOR</role>
  <email>AUTHOR@GMAIL.COM</email>
  <password>author123</password>
  <first_name>Autor</first_name>
  <middle-name>Aut</middle-name>
  <last-name>lAutoric</last-name>
  <expertises>
    <expertise>Chemistry</expertise>
  </expertises>
  <publications>
    <publicationID>Face_Detection</publicationID>
  </publications>
</User>
