=== zrnkemiki/XML_VS/xscience/src/main/resources/data/proba/publication.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
    targetNamespace="https://www.xscience.com/data/publication.xsd"
    xmlns:pbl="https://www.xscience.com/data/publication.xsd"
    xmlns:pred="https://www.xscience.com/data/publication/predicate/">

    <xs:element name="Publication"> 
        <xs:complexType>
            <xs:sequence>
                <xs:element name="MetaData">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="field_of_study" type="xs:string"/>
                            <xs:element default="RESEARCH_PAPER" name="paper_type">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:restriction base="pbl:paperType">
                                            <xs:enumeration value="RESEARCH_PAPER"/>
                                            <xs:enumeration value="VIEWPOINT"/>
                                            <xs:enumeration value="TECHNICAL_PAPER"/>
                                            <xs:enumeration value="CONCEPTUAL_PAPER"/>
                                            <xs:enumeration value="CASE_STUDY"/>
                                            <xs:enumeration value="LITERATURE_REVIEW"/>
                                            <xs:enumeration value="GENERAL_REVIEW"/>
                                        </xs:restriction>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="received" type="pbl:dateType"/>
                            <xs:element name="revisied" type="pbl:dateType"/>
                            <xs:element name="accepted" type="pbl:dateType"/>
                            <xs:element name="status">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:restriction base="pbl:statusType">
                                            <xs:enumeration value="UPLOADED"/>
                                            <xs:enumeration value="REJECTED"/>
                                            <xs:enumeration value="REVISED"/>
                                            <xs:enumeration value="ACCEPTED"/>
                                            <xs:enumeration value="RECEIVED"/>
                                            <xs:enumeration value="WITHDRAWN"/>
                                        </xs:restriction>
                                    </xs:simpleContent>
                                    
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="keywords">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element maxOccurs="10" name="keyword">
                                            <xs:complexType>
                                                <xs:simpleContent>
                                                    <xs:restriction base="pbl:keywordType">
                                                        <xs:minLength value="1"/>
                                                        <xs:maxLength value="40"/>
                                                    </xs:restriction>
                                                </xs:simpleContent>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Title">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:minLength value="1"/>
                            <xs:maxLength value="100"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="Author" maxOccurs="unbounded" type="pbl:TAuthor"> </xs:element>
                <xs:element name="Abstract">
                    <xs:complexType>
                        <xs:choice maxOccurs="unbounded">
                            <xs:element name="content" type="pbl:TStyle"/>
                            <xs:element name="quote" type="pbl:TQuote"/>
                        </xs:choice>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Content">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element maxOccurs="unbounded" name="Paragraph">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="Paragraph_title">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:minLength value="1"/>
                                                    <xs:maxLength value="50"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="Paragraph_content"
                                            type="pbl:TParagraphContent"> </xs:element>
                                    </xs:sequence>
                                    <xs:attribute name="id" type="xs:ID"/>
                                    <xs:attribute default="1" name="level">
                                        <xs:simpleType>
                                            <xs:restriction base="xs:positiveInteger">
                                                <xs:maxInclusive value="5"/>
                                            </xs:restriction>
                                        </xs:simpleType>
                                    </xs:attribute>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="References">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element maxOccurs="unbounded" name="Reference" type="pbl:TReference">
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Corresponding_author" type="pbl:TAuthor"/>
            </xs:sequence>
            <xs:attribute default="en-US" name="language" type="xs:language"/>
            <xs:attribute name="id" type="xs:ID"/>
            <xs:attribute name="about"/>
            <xs:attribute name="vocab"/>
            
            
        </xs:complexType>
    </xs:element>
    <xs:complexType name="TName">
        <xs:sequence>
            <xs:element name="First_name">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:minLength value="1"/>
                        <xs:maxLength value="20"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element maxOccurs="unbounded" minOccurs="0" name="Middle_name">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:minLength value="1"/>
                        <xs:maxLength value="20"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="Last_name">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:minLength value="1"/>
                        <xs:maxLength value="30"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="TAffiliation">
        <xs:sequence>
            <xs:choice>
                <xs:element name="Organization">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:minLength value="1"/>
                            <xs:maxLength value="100"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="University">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:minLength value="1"/>
                            <xs:maxLength value="50"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
            </xs:choice>
            <xs:element minOccurs="0" name="State">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:minLength value="1"/>
                        <xs:maxLength value="40"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="City">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:minLength value="1"/>
                        <xs:maxLength value="40"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="Country">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:minLength value="1"/>
                        <xs:maxLength value="30"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="TAuthor">
        <xs:sequence>
            <xs:element name="Name" type="pbl:TName"/>
            <xs:element name="Affiliation" type="pbl:TAffiliation"> </xs:element>
            <xs:element name="Academic_degree" type="xs:string"/>
            <xs:element name="Email">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:pattern value="[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="PhoneNumber">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:pattern value="[+]*[0-9]{20}"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="Signature" type="xs:base64Binary"/>
        </xs:sequence>
        <xs:attribute name="rel"/>
        <xs:attribute name="href"/>
    </xs:complexType>
    <xs:complexType name="TReference">
        <xs:sequence>
            <xs:element name="Author">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:minLength value="1"/>
                        <xs:maxLength value="50"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="Year">
                <xs:simpleType>
                    <xs:restriction base="xs:positiveInteger">
                        <xs:minInclusive value="1"/>
                        <xs:maxInclusive value="2200"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="Title">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:minLength value="0"/>
                        <xs:maxLength value="70"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="Place">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:minLength value="1"/>
                        <xs:maxLength value="50"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="Book_editor" minOccurs="0">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:minLength value="1"/>
                        <xs:maxLength value="30"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element default="BOOK_REFERENCE" name="Reference_type">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="BOOK_REFERENCE"/>
                        <xs:enumeration value="BOOK_CHAPTER_REFERENCE"/>
                        <xs:enumeration value="JOURNAL_REFERENCE"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="Chapter_title" minOccurs="0">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:minLength value="1"/>
                        <xs:maxLength value="50"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="Pages" minOccurs="0">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:minLength value="1"/>
                        <xs:maxLength value="30"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="Article_title" minOccurs="0">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:minLength value="1"/>
                        <xs:maxLength value="50"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="Journal_name" minOccurs="0">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:minLength value="1"/>
                        <xs:maxLength value="50"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="Volume_issue" minOccurs="0">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:minLength value="1"/>
                        <xs:maxLength value="30"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
        <xs:attribute name="id" type="xs:ID"/>
    </xs:complexType>
    <xs:complexType mixed="true" name="TStyle">
        <xs:choice maxOccurs="unbounded" minOccurs="0">
            <xs:element name="Bold" type="pbl:TStyle"/>
            <xs:element name="Italic" type="pbl:TStyle"/>
            <xs:element name="Underline" type="pbl:TStyle"/>
        </xs:choice>
    </xs:complexType>
    <xs:complexType name="TQuote">
        <xs:sequence>
            <xs:element name="Source" type="xs:string"/>
            <xs:element name="Quote_content" type="xs:string"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:ID"/>
    </xs:complexType>
    <xs:complexType name="TFigure">
        <xs:sequence>
            <xs:element name="Description" type="xs:string"/>
            <xs:element maxOccurs="unbounded" name="Image" type="xs:base64Binary"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:ID"/>
    </xs:complexType>
    <xs:complexType name="TList">
        <xs:sequence>
            <xs:element maxOccurs="unbounded" name="List_item" type="pbl:TStyle"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:string"/>
        <xs:attribute name="ordered" type="xs:boolean"/>
        <xs:attribute default="1" name="ordered_style">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:enumeration value="A"/>
                    <xs:enumeration value="a"/>
                    <xs:enumeration value="I"/>
                    <xs:enumeration value="i"/>
                    <xs:enumeration value="1"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
        <xs:attribute default="BULLET" name="unordered_style">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:enumeration value="BULLET"/>
                    <xs:enumeration value="CIRCLE"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
    </xs:complexType>
    <xs:complexType name="TTable">
        <xs:sequence>
            <xs:element name="Description" type="xs:string"/>
            <xs:element maxOccurs="unbounded" name="Row">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element maxOccurs="unbounded" name="Cell" type="xs:string"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
        <xs:attribute name="id" type="xs:ID"/>
    </xs:complexType>

    <xs:complexType name="paperType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="property" type="xs:string"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="dateType">
        <xs:simpleContent>
            <xs:extension base="xs:date">
                <xs:attribute name="property" type="xs:string"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="statusType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="property" type="xs:string"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="keywordType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="property" type="xs:string"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:complexType mixed="true" name="TParagraphContent">
        <xs:choice maxOccurs="unbounded">
            <xs:element name="Quote" type="pbl:TQuote"/>
            <xs:element name="Figure" type="pbl:TFigure"/>
            <xs:element name="List" type="pbl:TList"/>
            <xs:element name="Table" type="pbl:TTable"/>
            <xs:element name="Style" type="pbl:TStyle"/>
        </xs:choice>
    </xs:complexType>
</xs:schema>

=== zrnkemiki/XML_VS/xscience/src/main/resources/data/proba/pbltest.xml
<?xml version="1.0" encoding="UTF-8"?>
<pbl:Publication xmlns:pbl="https://www.xscience.com/data/publication.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://www.xscience.com/data/publication.xsd publication.xsd ">
  <pbl:MetaData>
    <pbl:field_of_study>pbl:field_of_study</pbl:field_of_study>
    <pbl:paper_type>RESEARCH_PAPER</pbl:paper_type>
    <pbl:received>2001-01-01</pbl:received>
    <pbl:revisied>2001-01-01</pbl:revisied>
    <pbl:accepted>2001-01-01</pbl:accepted>
    <pbl:status>UPLOADED</pbl:status>
    <pbl:keywords>
      <pbl:keyword>pbl:keyword</pbl:keyword>
    </pbl:keywords>
  </pbl:MetaData>
  <pbl:Title>pbl:Title</pbl:Title>
  <pbl:Author>
    <pbl:Name>
      <pbl:First_name>pbl:First_name</pbl:First_name>
      <pbl:Last_name>pbl:Last_name</pbl:Last_name>
    </pbl:Name>
    <pbl:Affiliation>
      <pbl:Organization>pbl:Organization</pbl:Organization>
      <pbl:City>pbl:City</pbl:City>
      <pbl:Country>pbl:Country</pbl:Country>
    </pbl:Affiliation>
    <pbl:Academic_degree>pbl:Academic_degree</pbl:Academic_degree>
    <pbl:Email>ASD@GMAIL.COM</pbl:Email>
    <pbl:PhoneNumber>+38112312312312312312</pbl:PhoneNumber>
    <pbl:Signature>MA==</pbl:Signature>
  </pbl:Author>
  <pbl:Abstract>
    <pbl:content/>
  </pbl:Abstract>
  <pbl:Content>
    <pbl:Paragraph>
      <pbl:Paragraph_title>pbl:Paragraph_title</pbl:Paragraph_title>
      <pbl:Paragraph_content>
        <pbl:Quote>
          <pbl:Source>pbl:Source</pbl:Source>
          <pbl:Quote_content>pbl:Quote_content</pbl:Quote_content>
        </pbl:Quote>
      </pbl:Paragraph_content>
    </pbl:Paragraph>
  </pbl:Content>
  <pbl:References>
    <pbl:Reference>
      <pbl:Author>pbl:Author</pbl:Author>
      <pbl:Year>1</pbl:Year>
      <pbl:Title>pbl:Title</pbl:Title>
      <pbl:Place>pbl:Place</pbl:Place>
      <pbl:Reference_type>BOOK_REFERENCE</pbl:Reference_type>
    </pbl:Reference>
  </pbl:References>
  <pbl:Corresponding_author>
    <pbl:Name>
      <pbl:First_name>pbl:First_name</pbl:First_name>
      <pbl:Last_name>pbl:Last_name</pbl:Last_name>
    </pbl:Name>
    <pbl:Affiliation>
      <pbl:Organization>pbl:Organization</pbl:Organization>
      <pbl:City>pbl:City</pbl:City>
      <pbl:Country>pbl:Country</pbl:Country>
    </pbl:Affiliation>
    <pbl:Academic_degree>pbl:Academic_degree</pbl:Academic_degree>
    <pbl:Email>SSS@GMAIL.COM</pbl:Email>
    <pbl:PhoneNumber>+38112312312312312312</pbl:PhoneNumber>
    <pbl:Signature>MA==</pbl:Signature>
  </pbl:Corresponding_author>
</pbl:Publication>

=== zrnkemiki/XML_VS/xscience/src/main/resources/data/valid-xml/Facial_req.xml
<?xml version="1.0" encoding="UTF-8"?>
<Publication about="" id="idvalue0" language="en-US" vocab="" xmlns="https://www.xscience.com/data/publication.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://www.xscience.com/data/publication.xsd ../xsd/publication.xsd ">
  <MetaData>
    <field_of_study>field_of_study</field_of_study>
    <paper_type property="">RESEARCH_PAPER</paper_type>
    <received property="">2001-01-01</received>
    <revisied property="">2001-01-01</revisied>
    <accepted property="">2001-01-01</accepted>
    <status property="">UPLOADED</status>
    <keywords>
      <keyword property="">keyword</keyword>
    </keywords>
  </MetaData>
  <Title>Facial req</Title>
  <Author href="" rel="">
    <Name>
      <First_name>First_name</First_name>
      <Last_name>Last_name</Last_name>
    </Name>
    <Affiliation>
      <Organization>Organization</Organization>
      <City>City</City>
      <Country>Country</Country>
    </Affiliation>
    <Academic_degree>Academic_degree</Academic_degree>
    <Email>DZOVAN@GMAIL.COM</Email>
    <PhoneNumber>+12341234123165453532</PhoneNumber>
    <Signature>MA==</Signature>
  </Author>
  <Abstract>
    <content/>
  </Abstract>
  <Content>
    <Paragraph id="idvalue1" level="1">
      <Paragraph_title>Paragraph_title</Paragraph_title>
      <Paragraph_content>
        <Quote id="idvalue2">
          <Source>Source</Source>
          <Quote_content>Quote_content</Quote_content>
        </Quote>
      </Paragraph_content>
    </Paragraph>
  </Content>
  <References>
    <Reference id="idvalue3">
      <Author>Author</Author>
      <Year>1</Year>
      <Title>Title</Title>
      <Place>Place</Place>
      <Reference_type>BOOK_REFERENCE</Reference_type>
    </Reference>
  </References>
  <Corresponding_author href="" rel="">
    <Name>
      <First_name>First_name</First_name>
      <Last_name>Last_name</Last_name>
    </Name>
    <Affiliation>
      <Organization>Organization</Organization>
      <City>City</City>
      <Country>Country</Country>
    </Affiliation>
    <Academic_degree>Academic_degree</Academic_degree>
    <Email>DOKICA@GAMIL.XOM</Email>
    <PhoneNumber>+12341234123165453532</PhoneNumber>
    <Signature>MA==</Signature>
  </Corresponding_author>
</Publication>
